name: crimson_labs
description: Testing Project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - lib/assets/icons
    - lib/assets/images
  
  fonts:
    - family: Gotham
      fonts:
        - asset: lib/assets/fonts/Gotham-Light.ttf
          weight: 200
        - asset: lib/assets/fonts/Gotham-Medium.ttf
        - asset: lib/assets/fonts/Gotham-Ultra.ttf
          weight: 900
